#!/bin/bash

lockwidth=256
lockheight=256
. "$HOME/.cache/wal/colors.sh"
pause_cmd='{ "command": ["set_property", "pause", true] }'

# Mute audio
pactl set-sink-mute @DEFAULT_SINK@ 1

# Pause MPD
mpc pause

# Pause mpv
for s in /tmp/mpv*socket; do
  echo "${pause_cmd}" | socat - $s
done

# Disable keyboard led
xset -led

# Pause dunst
killall -SIGUSR1 dunst

# Suspend monitors
xset dpms force suspend

# Lock screen
i3lock -i "$HOME/.config/i3/lock.png" \
  --nofork \
  --radius=124 --ring-width=7 \
  --insidecolor=00000000 --line-uses-inside \
  --insidevercolor=00000000 --veriftext="" \
  --insidewrongcolor=00000000 --wrongtext="" \
  --noinputtext="" \
  --ringcolor="${color4:1:6}ff" \
  --separatorcolor="${color4:1:6}ff" \
  --keyhlcolor="${color0:1:6}ff" \
  --bshlcolor="${color0:1:6}ff" \
  --ringvercolor="${color0:1:6}ff" \
  --ringwrongcolor="${color2:1:6}ff" \

# After-hours lockout
lockout_file="/tmp/i3-lockout"
if [[ -f "${lockout_file}" ]]; then
  # Relauch self
  nohup "${0}" &
  exit 1
fi

# Disable DPMS
xset -dpms

# Resume dunst
killall -SIGUSR2 dunst

# Enable keyboard led
xset led named "Scroll Lock"

# Unmute audio
pactl set-sink-mute @DEFAULT_SINK@ 0
