#!/bin/bash

lockwidth=256
lockheight=256
. "$HOME/.cache/wal/colors.sh"

# Disable keyboard led
xset -led

# Pause dunst
killall -SIGUSR1 dunst

i3lock -i "$HOME/.config/i3/lock.png" \
  --nofork \
  --radius=124 --ring-width=7 \
  --insidecolor=00000000 --line-uses-inside \
  --insidevercolor=00000000 --veriftext="" \
  --insidewrongcolor=00000000 --wrongtext="" \
  --noinputtext="" \
  --ringcolor="${color4:1:6}ff" \
  --separatorcolor="${color4:1:6}ff" \
  --keyhlcolor="${color0:1:6}ff" \
  --bshlcolor="${color0:1:6}ff" \
  --ringvercolor="${color0:1:6}ff" \
  --ringwrongcolor="${color2:1:6}ff" \

# Resume dunst
killall -SIGUSR2 dunst

# Enable keyboard led
xset led named "Scroll Lock"
