#!/bin/bash
#

feh --bg-fill "$HOME/.wallpaper"

i3-msg "append_layout $HOME/.config/i3/ws1.json"
i3-msg "exec dropbox"
i3-msg "exec owncloud"
i3-msg "exec keepass"
i3-msg "exec urxvt -title 'Discord' -e discurses"
i3-msg "exec telegram-desktop"
i3-msg "exec urxvt -title 'weechat' -e weechat"
i3-msg "exec thunderbird"

i3-msg "workspace 二"
i3-msg "exec urxvt"

i3-msg "workspace 三"
i3-msg "exec firefox"

#i3-msg "workspace 四"
#i3-msg "exec virt-manager"

i3-msg "workspace 一"

# Close Virt-Manager window but leave running in systray
#sleep 3s
#wmctrl -F -c "Virtual Machine Manager"
