#!/bin/bash
#
## notify-send wrapper for dunst / discurses`

REGEX_HIDE="in (buildapc|MSPs Я Us|The Synthetic Orchestra)#"
REGEX_OVERRIDE="(2[Ss]hirt|[Tt]woshirt|[Ww]izard.?[Kk]it)"

summary="${2:-?}"
body="${3:-}"
urgency="${5:-NORMAL}"

if [[ ! "${summary}" =~ $REGEX_HIDE || "${body}" =~ $REGEX_OVERRIDE ]]; then
  notify-send \
    --app-name="notify-send-wrapper" \
    --urgency="${urgency}" \
    "${summary}" "${body}"
fi

