#!/bin/bash
#
## Update TimeWarrior and Toggl at the same time

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

function check_activity() {
  # Ensure that all names are set or bail
  local name_check="${__timew_name:+w}${__toggl_name:+g}${__toggl_project:+p}"
  if [[ "${name_check}" != "wgp" ]]; then
    echo "ERROR: Unrecognized activity: '${2:-}'"
    exit 1
  fi
}

# Variables
__mode="$(echo "${1:-}" | tr "A-Z" "a-z")"
__regex_date='s/(T?[0-9]{2})([0-9]{2})$/\1:\2/'
__activities="${HOME}/.bin/time_activities"
__input_name="$(echo ${2:-} | tr "A-Z" "a-z")"
__start_date="$(echo "${3:-}" | sed -r "${__regex_date}")"
if [[ "${__mode}" == "stop" ]]; then
  __end_date="$(echo "${2:-}" | sed -r "${__regex_date}")"
else
  __end_date="$(echo "${4:-}" | sed -r "${__regex_date}")"
fi

# Set names
while read -r line; do
  __friendly_name="${line%% *}"
  if [[ "${__input_name}" != "${__friendly_name}" ]]; then
    # Try next line
    continue
  fi

  # Set names
  __timew_name="${line#* }"
  __timew_name="${__timew_name%% *}"
  __toggl_name="${line#* }"
  __toggl_name="${__toggl_name#* }"
  __toggl_project="${__toggl_name#* }"
  __toggl_name="${__toggl_name%% *}"
done <<< "$(sed -r 's/\s+/ /g; /^\s*$/d; /^#.*$/d' "${__activities}")"
unset __friendly_name

# Tests
#echo "Raw Input:      ${2:-}"
#echo "Fixed Input:    ${__input_name:-UNKNOWN}"
#echo "TimeW Name:     ${__timew_name:-UNKNOWN}"
#echo "Toggl Name:     ${__toggl_name:-UNKNOWN}"
#echo "Toggl Project:  ${__toggl_project:-UNKNOWN}"
#echo ""
#echo "Start Date:     ${__start_date:-UNKNOWN}"
#echo "End Date:       ${__end_date:-UNKNOWN}"
#echo ""

# Check run mode
case "${__mode}" in
  "add")
    check_activity
    if [[ "${__start_date}" == "" ]] || [[ "${__end_date}" == "" ]]; then
      echo "Please specify a date range for '${__toggl_name}'" 1>&2
      exit 1
    fi
    timew track "${__timew_name}" "${__start_date}" - "${__end_date}"
    toggl add "${__toggl_name}" @"${__toggl_project}" \
      "${__start_date}" "${__end_date}"
    ;;
  
  "now")
    toggl now
    timew
    ;;
  
  "start")
    check_activity
    timew start "${__timew_name}" "${__start_date}"
    toggl start "${__toggl_name}" @"${__toggl_project}" "${__start_date}"
    ;;
  
  "stop")
    timew stop "${__end_date}"
    toggl stop "${__end_date}"
    ;;

  *)
    if [[ "${__mode}" != "" ]]; then
      echo "ERROR: Unrecognized mode '${__mode}'"
      echo ""
    fi
    echo "Usage: $(basename "${0}") [OPTIONS]"
    echo ""
    echo "Options:"
    echo "    add   NAME DATE DATE"
    echo "    start NAME [DATE]"
    echo "    stop       [DATE]"
    ;;

esac

